import type { Metadata } from "next";
import { Inter } from "next/font/google";
require("@south-paw/typeface-minecraft");
import "./globals.css";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MMC Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " min-h-screen h-screen bg-stone-100 dark:bg-stone-800"}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
